/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface WilfriedGrid {
    }
}
declare global {
    interface HTMLWilfriedGridElement extends Components.WilfriedGrid, HTMLStencilElement {
    }
    var HTMLWilfriedGridElement: {
        prototype: HTMLWilfriedGridElement;
        new (): HTMLWilfriedGridElement;
    };
    interface HTMLElementTagNameMap {
        "wilfried-grid": HTMLWilfriedGridElement;
    }
}
declare namespace LocalJSX {
    interface WilfriedGrid {
    }
    interface IntrinsicElements {
        "wilfried-grid": WilfriedGrid;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "wilfried-grid": LocalJSX.WilfriedGrid & JSXBase.HTMLAttributes<HTMLWilfriedGridElement>;
        }
    }
}
